### ISSUE TITLE
Fix ranking filters

### ISSUE THREAD

**Issue by DavidAlvrz** [Arquisoft/wiq_es04a#271]
The ranking filters seem to be working badly.

**Comment by algarfer** [comment]
> The ranking filters seem to be working badly. 

@DavidAlvrz Animal, que este no es nuestro repo

**Comment by uo288543** [comment]
> > The ranking filters seem to be working badly.
> 
> @DavidAlvrz Animal, que este no es nuestro repo

![image](https://github.com/Arquisoft/wiq_es04a/assets/145331195/7e05b66b-58ec-4669-9b1f-b6e24fba1995)

**Comment by algarfer** [comment]
![image](https://github.com/Arquisoft/wiq_es04a/assets/58784148/5b4cffbc-a32a-4e56-9495-6fa0040b77eb)

**Comment by PabloGOP** [comment]
Subject: Appreciation for Your Contribution and Clarification Regarding Repository Reference

Dear [DavidAlvrz](https://github.com/DavidAlvrz),

I hope this message finds you well. Firstly, I wanted to express my sincere gratitude for your recent contribution to our repository. Your effort in identifying and reporting issues is invaluable to us, and we truly appreciate your dedication to improving our project.

Upon reviewing the issue you've published, which pertains to ranking filters, I wanted to clarify that as of now, our functionality does not include that specific feature. While I'm grateful for your diligence in bringing this to our attention, it's important to note that the issue seems to be related to another repository.

Nevertheless, your engagement with our project is highly commendable. Your willingness to explore and test our software demonstrates a genuine commitment to its improvement. Your feedback and insights are incredibly valuable to us as we strive to enhance the quality and functionality of our software.

In the spirit of collaboration and continuous improvement, I encourage you to continue exploring and testing our project. Whether it's identifying bugs, suggesting new features, or providing general feedback, your contributions play a vital role in shaping the future of our project.

Please feel free to reach out if you have any further questions or if there's anything specific you'd like to discuss regarding our repository. We're here to support you every step of the way and greatly value your involvement in our community.

Once again, thank you for your dedication and commitment to helping us create better software. We look forward to your continued engagement and collaboration.

ONE INGENIERÍA INFORMÁTICA DEL SOFTWARE, ONE WIQ

Warm regards,

Pablo.
